version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12

commands:
  version_bump:
    parameters:
      vertype:
        default: "minor"
        type: string
    steps:
      - run:
          name: Bump package <<parameters.vertype>> version
          command: npm version <<parameters.vertype>> -m "Bumped to %s"
  publish:
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

jobs:
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
            fingerprints:
              - "82:84:80:71:b5:50:26:10:7a:64:a9:9f:e2:93:c4:44"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Bump Package version
          command: npm version $CIRCLE_BRANCH
      - run:
          name: Update Github tags
          command: git push --tags
      - run:
          name: Deploy
          command: npm publish

      - version_bump:
          vertype: "patch"
      - publish
      - persist_to_workspace:
          root: ~/repo
          paths: .

  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm run test:ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2
  main:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: ^(?!v.*).*$