orbs:
  node: circleci/node@3.0.0
  npm-publisher: uraway/npm-publisher@0.2.0
workflows:
  node-tests:
    jobs:
      - node/test
  build_publish:
    jobs:
      - npm-publisher/publish-from-package-version:
          filters:
            branches:
              only: master
          fingerprints: be:d6:8a:b2:cd:7d:e5:c3:26:4f:66:2a:32:eb:aa:13
          post-publish-steps:
            - save_cache:
                key: 'v1-node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}'
                paths:
                  - node_modules
          pre-publish-steps:
            - restore_cache:
                keys:
                  - >-
                    v1-node-cache-{{ .Branch }}-{{ checksum "package-lock.json"
                    }}
                  - 'v1-node-cache-{{ .Branch }}'
                  - v1-node-cache-
            - run: npm install
            - run: npm build
          publish-token-variable: NPM_TOKEN
          push-git-tag: true
